//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newDatabaseApplicationTrying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKITEM
    {
        public string itemCode { get; set; }
        public string itemdesc { get; set; }
        public string itemsize { get; set; }
        public Nullable<decimal> itemcost { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> selling { get; set; }
    }
}
